### ISSUE TITLE
mistranslation from english to german language in brackets-link-file!

### ISSUE THREAD

**Issue by Lusch-Cologne** [pelatx/brackets-link-file#6]
Hello José, 

Thanks for creating brackets-link-file! 
It's a very helpful tool!

In the german translation i found two errors. The first one is confusing and should be exchanged

1. 
DROP_AREA_LABEL: "Link File (Dateien löschen)", > "Link File (Dateien ablegen)",

2.
HIDDEN_TOGGLE_LABEL: "Siehe versteckte", >  "Zeige verstecktes",

Thanks and best wishes,
Ludger

**Comment by pelatx** [comment]
Sorry for the delay @Lusch-Cologne.
I've been busy this days.

I will modify the translation soon.

Thank you.

**Comment by pelatx** [comment]
I have updated the extension and I have uploaded it. So I close this issue.

Thanks again @Lusch-Cologne.
